Strix/SonataCmsBundle/Form/StrixFileType.php
<?php

namespace Strix\SonataCmsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class StrixFileType extends AbstractType
{
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars = array_replace($view->vars, array(
            'type'  => 'file'
        ));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'compound' => false,
            'data_class' => null,
            'empty_data' => null,
        ));
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $view
            ->vars['multipart'] = true
        ;
    }

    public function getName()
    {
        return 'strix_file';
    }

    public function getParent()
    {
        return 'text';
    }
}

Strix/SonataCmsBundle/Resources/views/Admin/list_boolean_reverse.html.twig
{% extends '@SonataAdmin/CRUD/list_boolean.html.twig' %}

{% block field %}
    {% spaceless %}
        {% if value %}
            <a href="{{ admin.generateUrl(admin.normalizedCode ~ '_boolean_reverse', { id: object.id, field: field_description.name, unique: field_description.option('unique') }) }}"><span class="label label-success">{%- trans from 'SonataAdminBundle' %}label_type_yes{% endtrans -%}</span></a>
        {% else %}
            <a href="{{ admin.generateUrl(admin.normalizedCode ~ '_boolean_reverse', { id: object.id, field: field_description.name, unique: field_description.option('unique') }) }}"><span class="label label-danger">{%- trans from 'SonataAdminBundle' %}label_type_no{% endtrans -%}</span></a>
        {% endif %}
    {% endspaceless %}
{% endblock %}

Strix/SonataCmsBundle/Resources/views/Admin/list_raw.html.twig
{% extends '@SonataAdmin/CRUD/base_list_field.html.twig' %}

{%- block field %}{{ value|raw }}{% endblock -%}

Strix/SonataCmsBundle/Resources/views/Admin/list_slugs_ok.html.twig
{% extends '@SonataAdmin/CRUD/list_boolean.html.twig' %}

{% block field %}
    {% for language in admin.getCmsLanguages(true) %}
        <span class="label {% if admin.verifySlug(object, language.code) %}label-success{% else %}label-danger{% endif %}">{{ language.code }}</span>
    {% endfor %}
{% endblock %}

Strix/SonataCmsBundle/Resources/views/Admin/list_sortable_up_down.html.twig
{% extends '@SonataAdmin/CRUD/base_list_field.html.twig' %}

{%- block field %}
    <a href="{{ admin.generateUrl(admin.normalizedCode ~ '_sortable_up', { id: object.id }) }}"><i class="icon-arrow-up"></i></a>

    <a href="{{ admin.generateUrl(admin.normalizedCode ~ '_sortable_down', { id: object.id }) }}"><i class="icon-arrow-down"></i></a>
{% endblock field -%}

Strix/SonataCmsBundle/Resources/views/Admin/list_tree_down.html.twig
{% extends '@SonataAdmin/CRUD/base_list_field.html.twig' %}

{%- block field %}
    {% if object.parent and object.parent.children[object.parent.children|length - 1] != object %}
        <a href="{{ admin.generateUrl(admin.normalizedCode ~ '_down', { id: object.id }) }}">
            <i class="fa fa-caret-down"></i>
        </a>
    {% endif %}
{% endblock field -%}

Strix/SonataCmsBundle/Resources/views/Admin/list_tree_up.html.twig
{% extends '@SonataAdmin/CRUD/base_list_field.html.twig' %}

{%- block field %}
    {% if object.parent and object.parent.children[0] != object %}
        <a href="{{ admin.generateUrl(admin.normalizedCode ~ '_up', { id: object.id }) }}">
            <i class="fa fa-caret-up"></i>
        </a>
    {% endif %}
{% endblock field -%}